### ISSUE TITLE
Cannot start WallOfSheep module on the Wifi Pineapple Nano

### ISSUE THREAD

**Issue by kleo** [kirinrastogi/WallOfSheep#1]
Tested the WallOfSheep module on the Wifi Pineapple Nano using firmware 1.1.3

Not working on both internal storage and sd card, specifically the module start/enable button. No output from the module.

Tested again with the DWall module just to make sure the Pineapple is good, and the DWall module works.

**Comment by kirinrastogi** [comment]
I've only tested it on the tetra, I didn't know that there was a difference... I no longer own a tetra so I can't help that much. If you need some help look at the jquery code and do some similar stuff, all that this repo does is modify DWall's frontend. Sorry I can't help, good luck
